import { useState } from 'react'
import { Field } from '@base-ui-components/react/field'

export default function TwoFactorAuthForm() {
  const handleSubmit = (e) => {
    e.preventDefault()
    alert('2FA code submitted!')
  }

  return (
    <form onSubmit={handleSubmit} className="base-form">
      <Field.Root required className="base-field">
        <Field.Label className="base-label">6-digit security code</Field.Label>
        <Field.Control
          className="base-input"
          name="code"
          type="text"
          maxLength={6}
          pattern="[0-9]{6}"
          required
        />
        <span style={{ fontSize: '0.75rem', color: '#64748b' }}>
          Enter the code generated by your authenticator application.
        </span>
      </Field.Root>
      <label
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem',
          fontSize: '0.875rem',
        }}
      >
        <input type="checkbox" name="trustDevice" />
        Trust this device for 30 days
      </label>
      <button type="submit" className="base-button">
        Verify code
      </button>
    </form>
  )
}
