import { useState } from 'react'
import { Field } from '@ark-ui/react'

export default function TwoFactorAuthForm() {
  const handleSubmit = (e) => {
    e.preventDefault()
    alert('Submitted!')
  }

  return (
    <form onSubmit={handleSubmit} className="park-form">
      <Field.Root required className="park-field">
        <Field.Label className="park-label">6-digit security code</Field.Label>
        <Field.Input
          className="park-input"
          name="code"
          type="text"
          maxLength={6}
          pattern="[0-9]{6}"
          required
        />
        <span style={{ fontSize: '0.75rem', color: '#64748b' }}>
          Enter the code generated by your authenticator application.
        </span>
      </Field.Root>
      <label
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem',
          fontSize: '0.875rem',
        }}
      >
        <input type="checkbox" name="trustDevice" />
        Trust this device for 30 days
      </label>
      <button type="submit" className="park-button">
        Verify code
      </button>
    </form>
  )
}
