import { useState } from 'react'
import {
  Box,
  Button,
  Checkbox,
  FormControl,
  FormLabel,
  Input,
  Option,
  Select,
} from '@mui/joy'

export default function TwoFactorAuthForm() {
  const handleSubmit = (event) => {
    event.preventDefault()
    alert('2FA code submitted!')
  }

  return (
    <Box
      component="form"
      onSubmit={handleSubmit}
      sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}
    >
      <FormControl required>
        <FormLabel>6-digit security code</FormLabel>
        <Input
          name="code"
          type="text"
          slotProps={{ input: { maxLength: 6 } }}
          slotProps={{ input: { pattern: '[0-9]{6}' } }}
          required
        />
        <span style={{ fontSize: '0.75rem', color: '#64748b' }}>
          Enter the code generated by your authenticator application.
        </span>
      </FormControl>
      <Checkbox name="trustDevice" label="Trust this device for 30 days" />
      <Button type="submit">Verify code</Button>
    </Box>
  )
}
